// src/utils/countryCodes.js
export const countryCodes = [
    { code: '+93', country: 'Afganistán' },
    { code: '+27', country: 'África del Sur' },
    { code: '+355', country: 'Albania' },
    { code: '+49', country: 'Alemania' },
    { code: '+376', country: 'Andorra' },
    { code: '+244', country: 'Angola' },
    { code: '+1264', country: 'Anguila' },
    { code: '+1268', country: 'Antigua y Barbuda' },
    { code: '+966', country: 'Arabia Saudita' },
    { code: '+213', country: 'Argelia' },
    { code: '+54', country: 'Argentina' },
    { code: '+374', country: 'Armenia' },
    { code: '+297', country: 'Aruba' },
    { code: '+61', country: 'Australia' },
    { code: '+43', country: 'Austria' },
    { code: '+994', country: 'Azerbaiyán' },
    { code: '+1242', country: 'Bahamas' },
    { code: '+880', country: 'Bangladesh' },
    { code: '+1246', country: 'Barbados' },
    { code: '+973', country: 'Baréin' },
    { code: '+32', country: 'Bélgica' },
    { code: '+501', country: 'Belice' },
    { code: '+229', country: 'Benín' },
    { code: '+1441', country: 'Bermudas' },
    { code: '+375', country: 'Bielorrusia' },
    { code: '+95', country: 'Birmania' },
    { code: '+591', country: 'Bolivia' },
    { code: '+387', country: 'Bosnia y Herzegovina' },
    { code: '+267', country: 'Botsuana' },
    { code: '+55', country: 'Brasil' },
    { code: '+673', country: 'Brunéi' },
    { code: '+359', country: 'Bulgaria' },
    { code: '+226', country: 'Burkina Faso' },
    { code: '+257', country: 'Burundi' },
    { code: '+975', country: 'Bután' },
    { code: '+238', country: 'Cabo Verde' },
    { code: '+855', country: 'Camboya' },
    { code: '+237', country: 'Camerún' },
    { code: '+1', country: 'Canadá' },
    { code: '+974', country: 'Catar' },
    { code: '+235', country: 'Chad' },
    { code: '+56', country: 'Chile' },
    { code: '+86', country: 'China' },
    { code: '+357', country: 'Chipre' },
    { code: '+57', country: 'Colombia' },
    { code: '+269', country: 'Comoras' },
    { code: '+242', country: 'Congo' },
    { code: '+850', country: 'Corea del Norte' },
    { code: '+82', country: 'Corea del Sur' },
    { code: '+225', country: 'Costa de Marfil' },
    { code: '+506', country: 'Costa Rica' },
    { code: '+385', country: 'Croacia' },
    { code: '+53', country: 'Cuba' },
    { code: '+599', country: 'Curazao' },
    { code: '+45', country: 'Dinamarca' },
    { code: '+253', country: 'Yibuti' },
    { code: '+1809', country: 'República Dominicana' },
    { code: '+593', country: 'Ecuador' },
    { code: '+20', country: 'Egipto' },
    { code: '+503', country: 'El Salvador' },
    { code: '+971', country: 'Emiratos Árabes Unidos' },
    { code: '+291', country: 'Eritrea' },
    { code: '+421', country: 'Eslovaquia' },
    { code: '+386', country: 'Eslovenia' },
    { code: '+34', country: 'España' },
    { code: '+1', country: 'Estados Unidos' },
    { code: '+372', country: 'Estonia' },
    { code: '+251', country: 'Etiopía' },
    { code: '+63', country: 'Filipinas' },
    { code: '+358', country: 'Finlandia' },
    { code: '+679', country: 'Fiyi' },
    { code: '+33', country: 'Francia' },
    { code: '+241', country: 'Gabón' },
    { code: '+220', country: 'Gambia' },
    { code: '+995', country: 'Georgia' },
    { code: '+233', country: 'Ghana' },
    { code: '+350', country: 'Gibraltar' },
    { code: '+30', country: 'Grecia' },
    { code: '+502', country: 'Guatemala' },
    { code: '+224', country: 'Guinea' },
    { code: '+509', country: 'Haití' },
    { code: '+504', country: 'Honduras' },
    { code: '+36', country: 'Hungría' },
    { code: '+91', country: 'India' },
    { code: '+62', country: 'Indonesia' },
    { code: '+98', country: 'Irán' },
    { code: '+353', country: 'Irlanda' },
    { code: '+354', country: 'Islandia' },
    { code: '+972', country: 'Israel' },
    { code: '+39', country: 'Italia' },
    { code: '+81', country: 'Japón' },
    { code: '+962', country: 'Jordania' },
    { code: '+254', country: 'Kenia' },
    { code: '+996', country: 'Kirguistán' },
    { code: '+686', country: 'Kiribati' },
    { code: '+965', country: 'Kuwait' },
    { code: '+856', country: 'Laos' },
    { code: '+266', country: 'Lesoto' },
    { code: '+371', country: 'Letonia' },
    { code: '+961', country: 'Líbano' },
    { code: '+231', country: 'Liberia' },
    { code: '+218', country: 'Libia' },
    { code: '+423', country: 'Liechtenstein' },
    { code: '+370', country: 'Lituania' },
    { code: '+352', country: 'Luxemburgo' },
    { code: '+853', country: 'Macao' },
    { code: '+389', country: 'Macedonia' },
    { code: '+261', country: 'Madagascar' },
    { code: '+60', country: 'Malasia' },
    { code: '+265', country: 'Malaui' },
    { code: '+960', country: 'Maldivas' },
    { code: '+223', country: 'Malí' },
    { code: '+356', country: 'Malta' },
    { code: '+212', country: 'Marruecos' },
    { code: '+52', country: 'México' },
    { code: '+377', country: 'Mónaco' },
    { code: '+976', country: 'Mongolia' },
    { code: '+258', country: 'Mozambique' },
    { code: '+264', country: 'Namibia' },
    { code: '+977', country: 'Nepal' },
    { code: '+505', country: 'Nicaragua' },
    { code: '+227', country: 'Níger' },
    { code: '+234', country: 'Nigeria' },
    { code: '+47', country: 'Noruega' },
    { code: '+64', country: 'Nueva Zelanda' },
    { code: '+968', country: 'Omán' },
    { code: '+31', country: 'Países Bajos' },
    { code: '+92', country: 'Pakistán' },
    { code: '+507', country: 'Panamá' },
    { code: '+595', country: 'Paraguay' },
    { code: '+51', country: 'Perú' },
    { code: '+48', country: 'Polonia' },
    { code: '+351', country: 'Portugal' },
    { code: '+1', country: 'Puerto Rico' },
    { code: '+44', country: 'Reino Unido' },
    { code: '+236', country: 'República Centroafricana' },
    { code: '+420', country: 'República Checa' },
    { code: '+40', country: 'Rumania' },
    { code: '+7', country: 'Rusia' },
    { code: '+221', country: 'Senegal' },
    { code: '+65', country: 'Singapur' },
    { code: '+94', country: 'Sri Lanka' },
    { code: '+268', country: 'Suazilandia' },
    { code: '+27', country: 'Sudáfrica' },
    { code: '+46', country: 'Suecia' },
    { code: '+41', country: 'Suiza' },
    { code: '+597', country: 'Surinam' },
    { code: '+66', country: 'Tailandia' },
    { code: '+886', country: 'Taiwán' },
    { code: '+255', country: 'Tanzania' },
    { code: '+216', country: 'Túnez' },
    { code: '+90', country: 'Turquía' },
    { code: '+380', country: 'Ucrania' },
    { code: '+256', country: 'Uganda' },
    { code: '+598', country: 'Uruguay' },
    { code: '+998', country: 'Uzbekistán' },
    { code: '+58', country: 'Venezuela' },
    { code: '+84', country: 'Vietnam' },
    { code: '+967', country: 'Yemen' },
    { code: '+260', country: 'Zambia' },
    { code: '+263', country: 'Zimbabue' }
  ];